services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SECRET_KEY=django-insecure-ro*+#j2__s9vc6e)2#9bxm13r6#%*n0np_yjy8rt0900a1fqsv
      - DJANGO_DEBUG=True

  db:
    image: postgres:15
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
